services:
  bookmanager:
    image: ${DOCKER_REGISTRY-}bookmanager
    build:
      context: .
      dockerfile: BookManager/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=1234;Database=postgres
      - Redis__ConnectionString=redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: bookmanagerPostgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/db
    depends_on:
      - redis

volumes:
  postgres-data:
  redis-data:
  redis-insight-data:
